[build]
  publish = "."
  functions = "netlify/functions"


[[redirects]]
  from = "/capture_face"
  to = "netlify/functions"
  status = 200
  force = true

[[redirects]]
  from = "/recognize_face"
  to = "netlify/functions"
  status = 200
  force = true
